
# File: reFogConfig.yaml
# Author: Luke Burks
# Date: May 2018
# 
# Holds configuration values for interface.py and problemModel.py
#


###Data Collection
Interface:
  #Quality of Push Observations, {"NO","MEH","GOOD"}
  #NO: No push observations
  #MEH: Not super helpful
  #GOOD: On point, exact
  pushing: "NO"

  #Control Input Source, {"Human","MAP","WMAP,"POMCP"}
  #Human: Requires manual input with arrow keys
  #MAP: Takes shortest route to point of highest belief
  #WMAP: Weights belief peaks by their distance
  #POMCP: Calls JuliaPOMCP
  controlType: "MAP"

  #Number of points to retain in polygon fitting, {3-\inf}
  numSketchPoints: 8

  #Radius in pixels of drawn sketch points
  sketchDensity: 4

  ###Drone Params

  #Seconds before drone is available to use again, {1-\inf}
  droneWaitTime: 5

  #Pixel radius of area revealed by drone sweep, {1-\inf}
  droneViewRadius: 175

  #How often, in Hz, the front end requests a control action, {0.00001-\inf}
  controlFreq: 1

  #Maximum Frequency the controller can ask questions, {0.00001 - \inf}
  questionFreq: 0.25

  #Should the scout's view have a limited time? {True,False}
  refogScout: True
  
  #Should the Fog of War be reset after moving through? {True,False}
  refogCop: True

  #For Debugging, Shows the Target location on the fog
  cheatTarget: True

  #Where to save the data, must end in ".npy"
  dataSave: "../data/tmpInterfaceData2.npy"

  #Which file to load and play from
  #None: Collect Data
  #replayFile: "../data/tmpInterfaceData.npy"
  replayFile: None

###Model Params
Model:
  #If None, randomly chosen
  #Else: [0-437,0-754]
  copInitPose: [200,500]
  targetInitPose: [400,200]

  #Random Beliefs, if belNum is None, {1-40}
  numRandBel: 20

  #How far in each direction the robot clears fog {1-\inf}
  robotViewRadius: 100

  #How far in each direction the robot can catch the robot {1-\inf}
  robotCatchRadius: 25

  #How far the robots icon extends in each direction, in pixels, {1-\inf}
  robotSizeRadius: 10

  #Pixels per movement before transition adjustment, {1-\inf}
  robotNominalSpeed: 10

  #How far the targets icon extends in each direction, in pixels, {1-\inf}
  targetSizeRadius: 10

  #Number of steps in the comet trail, {0-\inf}
  breadCrumbLength: 50

  #Which pre-generated belief to use, {1-10}
  belNum: None

  #Standard Deviation of target position in pixels
  targetSpeed: 8

  #What governs the movement of the target? {"Stationary","Random","NCV"}
  targetMovementModel: "Random"
